services:
  freqgen:
    build: 
      context: .
      platforms: [linux]
    restart: unless-stopped
    ports:
      - 5000:8080
    volumes:
      - ./.env:/freqgen/.env
      - ./data:/freqgen/data
      - ./analytics:/freqgen/analytics
